---
collections:
  - name: amazon.aws
  - name: ansible.posix
  - name: ansible.utils
  - name: awx.awx
  - name: servicenow.itsm
  - name: servicenow.servicenow
  - name: community.mysql
  - name: community.general
  - name: community.aws
