---
collections:
  - name: amazon.aws
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.controller
  - name: servicenow.itsm
  - name: servicenow.servicenow
  - name: community.mysql
  - name: community.general
  - name: community.aws
  - name: zjleblanc.reporting
    version: ">=1.3.0"
  - name: redhat.rhel_system_roles
    version: 1.23.0
