---
collections:
  - name: amazon.aws
  - name: ansible.posix
  - name: ansible.utils
  - name: ansible.controller
    version: 4.5.0
  - name: servicenow.itsm
  - name: servicenow.servicenow
  - name: community.mysql
  - name: community.general
  - name: community.aws
