---
collections:
- name: community.general
- name: amazon.aws
- name: ansible.posix
- name: community.aws
- name: servicenow.itsm
- name: servicenow.servicenow
- name: awx.awx
- name: community.mysql
- name: community.windows
- name: ansible.utils