---
# These variables are set as Extra Vars
update_requested_item_comments: "Your Comments go here"
update_requested_item_state: 4
#
# Variable set at the workflow template
# ticket_number: ''
#
# Credential Types needed for this role
# ServiceNow ITSM Credential - This is a Custom Credential
