---
# Gather the start time to use in a later playbook
- name: Record the aws_sync_time
  delegate_to: 127.0.0.1
  register: aws_sync_time_pre
  ansible.builtin.command:
    cmd: "date '+%H:%M:%S'"

# Make the start time available to other playbooks
- name: Capture the aws_sync_time
  ansible.builtin.set_stats:
    data:
      aws_sync_time: "{{ aws_sync_time_pre.stdout }}"

- name: Get Linux Daily Demo instances
  register: instance_info
  amazon.aws.ec2_instance_info:
    region: "{{ region }}"
    filters:
      tag:Name: Linux Daily Demo
      instance-state-name: [running]

- name: Get an AAP API Token and store it as new_token
  register: new_token
  ansible.builtin.uri:
    url: https://{{ controller_url }}/api/v2/tokens/
    method: POST
    user: "{{ controller_user }}"
    password: "{{ controller_passwd }}"
    validate_certs: false
    force_basic_auth: true
    status_code: 201
    return_content: true

- name: Update the AAP Managed Inventory with the Linux Daily Demo servers
  loop: "{{ instance_info['instances'] }}"
  ansible.controller.host:
    controller_host: https://{{ controller_url }}
    controller_oauthtoken: "{{ new_token.json.token }}"
    validate_certs: false
    name: "{{ item['public_dns_name'] }}"
    inventory: "{{ managed_inventory_name }}"
    state: present
    enabled: true

- name: Create a group for our Linux Daily Demo servers
  loop: "{{ instance_info['instances'] }}"
  ansible.controller.group:
    controller_host: https://{{ controller_url }}
    controller_oauthtoken: "{{ new_token.json.token }}"
    validate_certs: false
    name: rheldemo
    description: Automation Controller Group
    inventory: "{{ managed_inventory_name }}"
    hosts: "{{ item['public_dns_name'] }}"
    preserve_existing_hosts: true

- name: Update runtime inventory
  loop: "{{ instance_info['instances'] }}"
  ansible.builtin.add_host:
    name: "{{ item['public_dns_name'] }}"
    groups:
      - rheldemo

- name: Capture public ip address
  ansible.builtin.set_fact:
    my_public_ip: "{{ instance_info.instances[0].public_ip_address }}"
