---
- name: Check for our mandatory variables
  # You can create a custom credential for the mandatory variables
  ansible.builtin.assert:
    that:
      - controller_url is defined
      - controller_user is defined
      - controller_passwd is defined
    fail_msg: "Please make sure your mandatory variables are set"
    success_msg: "All mandatory variables have been set"

- name: Get Linux Daily Demo instances
  register: instance_info
  amazon.aws.ec2_instance_info:
    region: "{{ region }}"
    filters:
      tag:Name: Linux Daily Demo
      instance-state-name: [running]

- name: Get an AAP API Token and store it as new_token
  register: new_token
  ansible.builtin.uri:
    url: https://{{ controller_url }}/api/v2/tokens/
    method: POST
    user: "{{ controller_user }}"
    password: "{{ controller_passwd }}"
    validate_certs: false
    force_basic_auth: true
    status_code: 201
    return_content: true

- name: Remove Linux Daily Demo server from the inventory
  loop: "{{ instance_info['instances'] }}"
  ansible.controller.host:
    controller_host: https://{{ controller_url }}
    controller_username: "{{ controller_user }}"
    controller_oauthtoken: "{{ new_token.json.token }}"
    name: "{{ item['public_dns_name'] }}"
    inventory: "{{ managed_inventory_name }}"
    state: absent

- name: Remove inventory host groups
  loop:
    - rheldemo
  ansible.controller.group:
    controller_host: https://{{ controller_url }}
    controller_username: "{{ controller_user }}"
    controller_oauthtoken: "{{ new_token.json.token }}"
    name: "{{ item }}"
    inventory: "{{ managed_inventory_name }}"
    state: absent
