---
- name: Get Linux Daily Demo instances
  register: instance_info
  amazon.aws.ec2_instance_info:
    region: "{{ region }}"
    filters:
      tag:Name: Linux Daily Demo
      instance-state-name: [running]

- name: Create a new token using username/password
  ansible.controller.token:
    controller_host: https://{{ controller_url }}
    controller_username: "{{ controller_user }}"
    controller_password: "{{ controller_passwd }}"
    validate_certs: false
    description: Daily Demo token
    scope: write
    state: present

- name: Remove Linux Daily Demo server from the inventory
  loop: "{{ instance_info['instances'] }}"
  ansible.controller.host:
    controller_host: https://{{ controller_url }}
    controller_oauthtoken: "{{ controller_token }}"
    name: "{{ item['public_dns_name'] }}"
    inventory: "{{ managed_inventory_name }}"
    state: absent

- name: Remove inventory host groups
  loop:
    - rheldemo
  ansible.controller.group:
    controller_host: https://{{ controller_url }}
    controller_oauthtoken: "{{ controller_token }}"
    name: "{{ item }}"
    inventory: "{{ managed_inventory_name }}"
    state: absent
