---
- name: Send an email with the link to the aap demo Server
  community.general.mail:
    host: "{{ smtpserver }}"
    port: "{{ smtp_port }}"
    secure: try
    username: "{{ smtp_username }}"
    password: "{{ smtp_password }}"
    subject: Ansible Automation Platform (AAP) Daily Demo - Linux
    body: "System {{ data]['my_server'] }} has been successfully provisioned using AAP. This URL will take you to the webserver: http://{{ my_server }} You can admin the machine here: https://{{ my_server }}:9090 or use ssh command to login: ssh ec2-user@{{ my_server }}"
    from: "{{ mailfrom }}"
    to: "{{ mailto }}"
    bcc: "{{ bccto }}"
