---
- name: Update the inventory
  hosts: localhost
  connection: local

  tasks:

    - name: Include the inventory role
      tags:
        - create
      ansible.builtin.include_role:
        name: inventory
