---
  - name: Control AWS instances
    hosts: localhost
    connection: local
    gather_facts: no
    vars:
       region: ''
       servername: ''

    tasks:

    - name: Get instances id with tag {{servername}} in {{region}}
      register: instance_info
      amazon.aws.ec2_instance_info:
       region: "{{region}}"
       filters:
         "tag:Name": "{{servername}}"
         instance-state-name: [ "running"]
         "tag:Contact": "{{my_email_address}}"

    - name: Print out instance info
      when: instance_info.instances[0].instance_id is defined
      ansible.builtin.debug:
         msg: "{{instance_info.instances[0].instance_id}}"
      
    - name: Setting ec2 {{servername}} to absent
      when: instance_info.instances[0].instance_id is defined
      amazon.aws.ec2_instance:
        region: "{{region}}"
        state: absent
        instance_ids: "{{instance_info.instances[0].instance_id}}"