- name: Server configration management is begining
  hosts: rheldemo
  become: true
  gather_facts: true

  roles:

    - role: zjleblanc.reporting.dnf
      vars:
        linux_patch_run_once: false
        linux_patch_become_publish: true
        linux_patch_output_remote_host: "{{ inventory_hostname }}"
        linux_patch_output_dest: "/var/www/html/patch.html"
