---
- name: Create the infrastructure we need
  hosts: localhost
  connection: local

  roles:

    - role: vm
    - role: inventory
    - role: get_instance_info

- name: Server configration management is begining
  hosts: rheldemo
  become: true
  gather_facts: true

  roles:

    - role: rhsm
      status: present
    - role: linux_post_install
    - role: linux_account_create
    - role: lamp_setup
    - role: website_setup
