---
- name: Create the infrastructure we need
  hosts: localhost
  connection: local

  roles:
    - role: vpc_create_aws
    - role: instance_create_aws
    - role: inventory_add_servers
    - role: get_instance_info

- name: Server configration management is begining
  hosts: rheldemo
  become: true
  gather_facts: true

  roles:

    - role: redhat_subscription_manager
      status: present
    - role: linux_post_install