---
- name: Create the infrastructure we need
  hosts: localhost
  connection: local

  # tasks:

  #   - name: VPC Create role
  #     ansible.builtin.include_role:
  #       name: vpc_create_aws

  #   - name: Create instance role
  #     ansible.builtin.include_role:
  #       name: instance_create_aws

  #   - name: Inventory add role
  #     ansible.builtin.include_role:
  #       name: inventory_add_servers

  #   - name: Get instance info
  #     ansible.builtin.include_role:
  #       name: get_instance_info

  roles:
    - role: vpc_create_aws
    - role: instance_create_aws
    - role: inventory_add_servers
    - role: get_instance_info

  post_tasks:

    - name: Show Gathered Facts
      ansible.builtin.debug:
        msg: "{{ hostvars['localhost'].ansible_facts }}"

- name: Server configration management is begining
  hosts: rheldemo
  become: true
  gather_facts: true

  pre_tasks:

    - name: Debug vpc_create_time
      ansible.builtin.debug:
        var: vpc_create_time

    - name: Debug machine_create_time
      ansible.builtin.debug:
        var: machine_create_time

    - name: Debug post_install_time
      ansible.builtin.debug:
        var: post_install_time

    - name: Debug lamp_time
      ansible.builtin.debug:
        var: lamp_time

    - name: Debug subscription_time
      ansible.builtin.debug:
        var: subscription_time

    - name: Debug insights_time
      ansible.builtin.debug:
        var: insights_time
  # tasks:

  #   - name: Red Hat Subscription Manager
  #     ansible.builtin.include_role:
  #       name: redhat_subscription_manager
  #     vars:
  #       status: present

  #   - name: Linux Post install
  #     ansible.builtin.include_role:
  #       name: linux_post_install

  #   - name: Account setup
  #     ansible.builtin.include_role:
  #       name: linux_account_create

  #   - name: LAMP setup
  #     ansible.builtin.include_role:
  #       name: lamp_setup

  #   - name: Website setup
  #     ansible.builtin.include_role:
  #       name: website_setup

  roles:

    - role: redhat_subscription_manager
      status: present
    - role: linux_post_install
    - role: linux_account_create
    - role: lamp_setup
    - role: website_setup
