---
- name: Create the infrastructure we need
  hosts: localhost
  connection: local

  roles:
    - role: vpc_create_aws
    - role: instance_create_aws
    - role: inventory_add_servers
    - role: get_instance_info

- name: Server configration management is begining
  hosts: rheldemo
  become: true
  gather_facts: true
  vars:
    vpc_create_time: "{{ hostvars['localhost']['vpc_create_time']['stdout'] }}"
    machine_create_time: "{{ hostvars['localhost']['machine_create_time']['stdout'] }}"

  pre_tasks:

    - name: Debug machine_create_time
      ansible.builtin.debug:
        var: machine_create_time

    - name: Debug post_install_time
      ansible.builtin.debug:
        var: post_install_time

    - name: Debug lamp_time
      ansible.builtin.debug:
        var: lamp_time

    - name: Debug subscription_time
      ansible.builtin.debug:
        var: subscription_time

    - name: Debug insights_time
      ansible.builtin.debug:
        var: insights_time

  roles:

    - role: redhat_subscription_manager
      status: present
    - role: linux_post_install
    - role: linux_account_create
    - role: lamp_setup
    - role: website_setup
