---
- name: Update a catalog item in ServiceNow
  hosts: localhost
  gather_facts: no
  
  tasks: 
  
    - name: Retrieve catalog request sysid
      servicenow.itsm.api_info:
        resource: sc_req_item
        sysparm_query: numberSTARTSWITH{{ ticket_number }}
      register: result

    - name: print the result
      ansible.builtin.debug:
        var: result

    - name: Update a catalog work notes and state in ServiceNow
      servicenow.itsm.api:
        action: patch
        resource: sc_req_item
        sys_id: "{{ result.record[0].sys_id }}"
        data:
          request_state: "{{ request_state | default(omit) }}"
          comments: "Provisioning details\n\nVPC Create Time: {{ vpc_create_time }}\n\nMachine Create Time: {{ machine_create_time }}
                     \n\nRedHat Subscription Time: {{ subscription_time }}\n\nPost Install Time: {{ post_install_time }}
                     \n\nRedHat Insights Time: {{ insights_time }}\n\nWebsite Start Time: {{ lamp_time }}\n\nPublic DNS Name: {{ my_server }}
                     \n\nPublic IP Address: {{ my_public_ip }}\n\nAWS AMI ID: {{ my_ami_id }}\n\nAWS Instance ID: {{ my_instance_id }}\n\nAWS Instance Type: {{ my_instance_type }}
                     \n\nAWS availability zone: {{ my_availability_zone }}"
          state: 3
        #delete me
