---
- name: Registering system with Satellite
  tags:
    - create
  block:

    # Gather the start time to use in a later playbook
    - name: Record the subscription_time
      delegate_to: 127.0.0.1
      register: subscription_time_pre
      changed_when: false
      ansible.builtin.command:
        cmd: "date '+%H:%M:%S'"

    # Make the start time available to other playbooks
    - name: Capture the subscription_time
      ansible.builtin.set_stats:
        data:
          subscription_time: "{{ subscription_time_pre.stdout }}"

    - name: Setting the hostname to the public hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Remove the rh-amazon-rhui-client rpm
      ansible.builtin.dnf:
        name: rh-amazon-rhui-client
        state: removed

    - name: Enable the rhsm repo
      changed_when: false
      ansible.builtin.shell:
        cmd: set -o pipefail && subscription-manager config --rhsm.manage_repos=1
        executable: /bin/bash

    - name: Installing katello-ca-consumer-latest.noarch.rpm from Satellite server
      ansible.builtin.dnf:
        name: http://{{ sat6_fqdn }}/pub/katello-ca-consumer-latest.noarch.rpm
        state: present
        disable_gpg_check: true

    - name: Registering server with Satellite
      community.general.redhat_subscription:
        state: present
        activationkey: "{{ activation_key }}"
        org_id: "{{ org_id }}"
        consumer_name: "{{ inventory_hostname }}"

    - name: Installing Satellite key for remote execution
      ansible.posix.authorized_key:
        user: ec2-user
        key: "{{ lookup('url', 'https://{{ sat6_fqdn}}:9090/ssh/pubkey', validate_certs=False, split_lines=False) }}"
        state: present

    - name: Register server with insights
      vars:
        rhc_insights:
          rhc_state: present
      ansible.builtin.import_role:
        name: redhat.rhel_system_roles.rhc

    # - name: Register with Red Hat Insights
    #   register: result
    #   changed_when: result.rc == 1
    #   failed_when: result.rc > 1
    #   ansible.builtin.command: insights-client --register

- name: Un-Registering system from Satellite and Insights
  tags:
    - remove
  block:

    - name: UN-Register and subscribe the system
      community.general.redhat_subscription:
        state: absent
        org_id: "{{ org_id }}"
        activationkey: "{{ activation_key }}"
        consumer_name: "{{ inventory_hostname }}"

    - name: UN-Register server with insights
      vars:
        rhc_state: absent
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.rhc

    # - name: UN-Register Red Hat Insights
    #   register: result
    #   changed_when: result.rc == 1
    #   failed_when: result.rc > 1
    #   ansible.builtin.command: insights-client --unregister
